#!/usr/bin/env bash
# Auto-generated by project-analyzer confirm --apply-entry
# Filters Java source file edits and emits a rule-check trigger to the current
# Claude Code session. No subprocess Claude invocation — the current session
# handles rule checking after receiving this output.

set -euo pipefail

HOOK_DATA=$(cat)
FILE_PATH=$(echo "$HOOK_DATA" | python3 -c \
  "import sys,json; d=json.load(sys.stdin); \
   print(d.get('tool_input',{}).get('file_path',''))" 2>/dev/null || true)

[[ -z "$FILE_PATH" ]] && exit 0
[[ "$FILE_PATH" != *.java ]] && exit 0
[[ "$FILE_PATH" == */src/test/* ]] && exit 0

PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
INDEX="$PROJECT_ROOT/.claude/rules/generated/00-index.md"
[ ! -f "$INDEX" ] && exit 0

echo "[project-analyzer] Rule check: $FILE_PATH"
echo "请检查代码是否符合项目规则文件，违规时自动修复或阻断。"
