#!/usr/bin/env bash
# Auto-generated by project-analyzer confirm --apply-entry
# Filters Java source file edits and emits a test-generation trigger to the
# current Claude Code session. No subprocess Claude invocation — the current
# session handles test generation after receiving this output.

set -euo pipefail

HOOK_DATA=$(cat)
FILE_PATH=$(echo "$HOOK_DATA" | python3 -c \
  "import sys,json; d=json.load(sys.stdin); \
   print(d.get('tool_input',{}).get('file_path',''))" 2>/dev/null || true)

[[ -z "$FILE_PATH" ]] && exit 0
[[ "$FILE_PATH" != *.java ]] && exit 0
[[ "$FILE_PATH" == */src/test/* ]] && exit 0

PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OBS="$PROJECT_ROOT/.claude/rules/analysis/testing-observations.md"
[ ! -f "$OBS" ] && exit 0

echo "[project-analyzer] Java source modified: $FILE_PATH"
echo "请按 test-generator 规范生成单元测试并运行。"
